# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a64b930c0cce4e4a56b43e82e5e3ef9e9a93df6bff047619913f37938cd3f3c263d24e38ff3d8dbedcc2cf060f8cef343c88c7f9041252f511e4a91ef2df677

test:
  secret_key_base: 93e12605a3d230995c779249bcd3475fd7c3a64e9ee8c61d2d62253c86b9ca2e144ca90be107b5cb1238ffa5570b5a1e3a7098a872bae909a310b01b1ce2d2ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
